export enum CategoriaDificuldade {
  LEITURA = 'LEITURA',
  ESCRITA = 'ESCRITA',
  MATEMATICA = 'MATEMATICA',
  ATENCAO = 'ATENCAO',
  COMPORTAMENTO = 'COMPORTAMENTO',
  COMUNICACAO = 'COMUNICACAO',
  COORDENACAO_MOTORA = 'COORDENACAO_MOTORA',
  MEMORIA = 'MEMORIA',
  ORGANIZACAO = 'ORGANIZACAO',
  OUTRO = 'OUTRO',
} 