export enum CategoriaInstrumento {
  ACADEMICO = 'ACADEMICO',
  COMPORTAMENTAL = 'COMPORTAMENTAL',
  SOCIOEMOCIONAL = 'SOCIOEMOCIONAL',
  COGNITIVO = 'COGNITIVO',
  LINGUAGEM = 'LINGUAGEM',
  MOTOR = 'MOTOR',
  ATENCAO = 'ATENCAO',
  OUTRO = 'OUTRO',
} 